packages:
  - code/apps/*
  - code/packages/*

catalog:
  hono: 4.7.6
  json-rpc-2.0: 1.7.0
  typescript: 5.8.3
  vite: 6.2.6

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - sharp
  - workerd
