packages:
  - code/apps/*
  - code/packages/*

catalog:
  '@babylonjs/core': 8.2.0
  '@babylonjs/loaders': 8.2.0
  '@vitejs/plugin-react': 4.3.4
  hono: 4.7.6
  json-rpc-2.0: 1.7.0
  react: 19.1.0
  react-dom: 19.1.0
  typescript: 5.8.3
  vite: 6.2.6

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - sharp
  - workerd
